apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: currency-microservices/k8s-api-gateway:0.3.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: k8s-api-gateway-server
          envFrom:
            - configMapRef:
                name: api-gateway
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              port: 8765
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8765
              path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  ports:
    - port: 8765
      protocol: TCP
      targetPort: 8765
  selector:
    app: api-gateway
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  APPLICATION_ENV: default
  EXCHANGE_URI: http://currency-exchange
  CONVERSION_URI: http://currency-conversion
  API_GETWAY_URI: http://api-gateway
  EUREKA_URI: http://naming-server
  SPRING_CLOUD_URI: http://spring-cloud
  ZIPKIN_URI: http://zipkin-server
  LOKI_URI: http://loki:3100
  TEMPO_URI: http://tempo:4318/v1/traces
  KEYCLOAK_URI: http://keycloak:8080
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: default
