apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
        - image: currency-microservices/k8s-currency-exchange-service:0.2.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: k8s-currency-exchange-service
          envFrom:
            - configMapRef:
                name: currency-exchange
          readinessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  APPLICATION_ENV: native
  EXCHANGE_URI: http://currency-exchange
  CONVERSION_URI: http://currency-conversion
  API_GETWAY_URI: http://api-gateway
  EUREKA_URI: http://naming-server
  SPRING_CLOUD_URI: http://spring-cloud
  ZIPKIN_URI: http://zipkin-server
  LOKI_URI: http://loki:3100
kind: ConfigMap
metadata:
  name: currency-exchange
  namespace: default
