apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: naming-server
  name: naming-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naming-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
        - image: currency-microservices/k8s-naming-server:0.1.3-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: k8s-naming-server
          envFrom:
            - configMapRef:
                name: naming-server
          # env:
          #   - name: CURRENCY_EXCHANGE_URI
          #     value: http://currency-exchange
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: naming-server
  name: naming-server
  namespace: default
spec:
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: naming-server
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  APPLICATION_ENV: native
  EXCHANGE_URI: http://currency-exchange
  CONVERSION_URI: http://currency-conversion
  API_GETWAY_URI: http://api-gateway
  EUREKA_URI: http://naming-server
  SPRING_CLOUD_URI: http://spring-cloud
kind: ConfigMap
metadata:
  name: naming-server
  namespace: default
