apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: list-properties
  name: list-properties
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-properties
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: list-properties
    spec:
      containers:
        - image: currency-microservices/k8s-list-properties-cloud:0.3.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: k8s-list-properties-service
          envFrom:
            - configMapRef:
                name: list-properties
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              port: 8200
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8200
              path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: list-properties
  name: list-properties
  namespace: default
spec:
  ports:
    - port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    app: list-properties
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  APPLICATION_ENV: default
  EXCHANGE_URI: http://currency-exchange
  CONVERSION_URI: http://currency-conversion
  API_GETWAY_URI: http://api-gateway
  EUREKA_URI: http://naming-server
  SPRING_CLOUD_URI: http://spring-cloud
  ZIPKIN_URI: http://zipkin-server
  LOKI_URI: http://loki:3100
  TEMPO_URI: http://tempo:4318/v1/traces
  RABBIT_HOST: rabbitmq
  RABBIT_PORT: "5672"
  RABBIT_USERNAME: guest
  RABBIT_PASSWORD: guest
kind: ConfigMap
metadata:
  name: list-properties
  namespace: default
