apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: spring-cloud
  name: spring-cloud
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-cloud
    spec:
      containers:
        - image: currency-microservices/k8s-spring-cloud-server:0.3.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: k8s-spring-cloud-server
          env:
            - name: ZIPKIN_URI
              value: http://zipkin-server
            - name: LOKI_URI
              value: http://loki:3100
            - name: TEMPO_URI
              value: http://tempo:4318/v1/traces
          volumeMounts:
            - name: config-volume
              mountPath: /configs
      volumes:
        - name: config-volume
          configMap:
            name: spring-cloud-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-cloud
  name: spring-cloud
  namespace: default
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: spring-cloud
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-config
  namespace: default
data:
  application.yml: |
    spring:
      cloud:
        config:
          server:
            native:
              search-locations: file:/configs
  list-properties-cloud.yml: |
    liste-services-uri:
      envProfil: dev
      uriConversion: http://currency-conversion
      uriExchange: http://currency-exchange
      uriApiGetway: http://api-gateway
      uriSpringCloud: http://spring-cloud
