---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  config.yaml: |+
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    query_frontend:
      search:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
      trace_by_id:
        duration_slo: 5s

    # Remove querier section for single instance deployment

    ingester:
      max_block_duration: 30m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    compactor:
      compaction:
        block_retention: 336h

    storage:
      trace:
        backend: local
        wal:
          path: /tmp/tempo/wal
        local:
          path: /tmp/tempo/blocks

    overrides:
      defaults:
        metrics_generator:
          processors: []  # Disable for simplicity

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - image: grafana/tempo:2.3.1
          name: tempo
          command: ["/tempo", "-config.file=/etc/config/tempo/config.yaml"]
          ports:
            - containerPort: 3200
              name: http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: config
              mountPath: /etc/config/tempo
            - name: tempo-storage
              mountPath: /tmp/tempo
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: tempo-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: otlp-grpc
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: otlp-http
    - protocol: TCP
      port: 3200
      targetPort: 3200
      name: http
  selector:
    app: tempo
